try{
    console.log(value);
}catch(error){
    console.log(error);
}